# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/.emacs.d/bin"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  # GitHub アクションの依存関係を維持する
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/.emacs.d/bin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/.emacs.d/bin"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
