(with-eval-after-load 'consult
  (setq consult-narrow-key ">")
  (setq consult-widen-key "<")
  (setq consult-preview-key "M-.")
  (global-set-key (kbd "C-;") 'consult-buffer)
  (global-set-key [remap goto-line] 'consult-goto-line)
  (global-set-key (kbd "C-M-s") 'consult-line)
  (global-set-key (kbd "C-x C-d") 'consult-dir)
  (defun consult-howm-do-ag ()
    (interactive)
    (consult-ripgrep howm-directory))
  (global-set-key (kbd "C-z s") 'consult-howm-do-ag)
  (global-set-key (kbd "C-z l") 'consult-ls-git))
