name: CI
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths:
      - '**'
      - '!*.md'
  pull_request:
    paths:
      - '**'
      - '!*.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - "29.3"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}
    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'
    - run: mv .emacs.d/el-get/.gitkeep .emacs.d/el-get/.status.el
    - run: composer install
      working-directory: .emacs.d/bin
    - run: yarn install --frozen-lockfile
      working-directory: .emacs.d/bin
    - run: pip3 install -r bin/requirements.txt
      working-directory: .emacs.d
    - run: emacs -Q -l .emacs.d/early-init.el -l .emacs.d/init.el  --batch
    - name: Eask
      run: |
        eask clean all
        eask compile

